   ; comentário de teste no topo
    section     text
TAM    : EQU 10
ZERO: EQU 0
IF TAM
LOAD OLD_DATA
IF ZERO
INPUT  OLD_DATA
L1      :
L2   :
L3:     
    DIV DOIS ;comentário de teste aqui
STORE  NEW_DATA
MULT DOIS
STORE TMP_DATA
    LOAD         OLD_DATA   
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA, OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
SECTION DATA
DOIS:       
    CONST TAM
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE
; comentário de teste no fim